enriclluelles/route_translator

README.md

This way it is clearer that the translation also works for non-restful routes

adding non-restful route example

---

lib/route_translator.rb
lib/route_translator/translator.rb
test/routing_test.rb
test/support/configuration_helper.rb

Our app does not specify available_locales because we allow users to post in any locale they wish and then we do some translation magic later on. However, that doesn't necessarily mean we want all our routes translated for all locales in the Rails stack. In our case, we only want to provide translated routes for two languages.
This configuration setting will allow the gem to accept which locales the end-user would like to translate in the event that they haven't specified `available_locales` in their Rails stack.

Specify locales in config options.

---

lib/route_translator/extensions/action_controller.rb
lib/route_translator/translator.rb
test/routing_test.rb
test/test_helper.rb

PR #45 fixed issues #27 and #71. But related code was removed from
master at some point. Bring it back.

Fix regression

---

lib/route_translator/translator.rb
test/dummy/app/controllers/dummy_controller.rb
test/dummy/app/views/dummy/optional.html.erb
test/dummy/app/views/dummy/prefixed_optional.html.erb
test/dummy/config/routes.rb
test/integration/generated_path_test.rb

Hi,
first of all; thanks for your awesome work on this gem!
The gem works fine with rails routes and optional parameters; e.g.
/some(/:optional)
However, when I was porting over one of our applications, I noticed that something broke when using this gem (I was previously using another gem for route translation).
/some(/page-:optional)
The issue lies in the **/page-** static prefix of the optional parameter. While this is fully supported in rails, the regex functions and translation routines in this gem, don't take the possible "prefix" into account.
If expanded the test from _a colon in the beginning_ of a segment to _somewhere_ in the segment. I wrote the necessary tests and they all passes again!
Would you please consider to merge this into your repository?
Please let me know if you …

Optional parameters with prefix breaks

---

.rubocop.yml
lib/route_translator/translator.rb
test/dummy/app/controllers/dummy_controller.rb
test/dummy/config/routes.rb
test/integration/host_locales_test.rb

Identical to #115 (solving #95).
I've tested 4.2.1 with this fix and it seems to work just as with 4.0.0. It has not been deployed to production yet, but specs are passing.

Fixing native path generation issue

---

README.md

The `available_locales` setting wasn't mentioned in the README. Easy to find out by reading the source but somewhat cumbersome, so I added it.
Thanks for a very useful gem!

Mention available_locales config in README :book:

---

lib/route_translator/translator.rb
test/routing_test.rb

#58 Solved the issue with `people.:format` but it didn't work for something like `people:.name` or `people/.:name`.
This solves the issue for every situation.

Generate correct route when a segment is preceded by a dot

---

README.md
lib/route_translator.rb
lib/route_translator/translator/path.rb
test/dummy/config/locales/all.yml
test/integration/generated_path_test.rb
test/integration/locale_path_segment_test.rb
test/locales/routes.yml
test/routing_test.rb
test/support/configuration_helper.rb

(originally PR #137)
I have a requirement to use "IKEA-style" locale segments that look like:
`/<region>/<language>` e.g. `/gb/en/foo/bar` for the locale: `en-GB`
I've created this PR to allow anyone to supply their own Proc for generating the locale segment of the path.
For my needs I can do the following:
```ruby
RouteTranslator.config do |config|
config.locale_segment_proc = ->(locale) { locale.to_s.downcase.split('-').reverse.join('/') }
end
```

support custom locale path segments, i.e. /uk/en/widgets

---

test/integration/locale_path_segment_test.rb

Following rails/rails-dom-testing@06adecc which removes assert_tag it
seems the new API for this is assert_select provided with a CSS selector.
This seems to get all the tests passing on the feature/rails5 branch.

Update assert_tag to assert_select

---

lib/route_translator/translator.rb
test/routing_test.rb

When a constraint is callable it will fail with NoMethodError due to
`[]=` not being implemented.  Instead we return an empty hash.

Fix issue with callable constraints

---

lib/route_translator/translator.rb
test/routing_test.rb

When changing options_constraints to an empty hash for #translations_for
it overrides the callable preventing the constraint from working in
rails. Instead of overriding the value we should only modify it if the
value responds to `[]=`.

Retain value of options_constraints if callable

---

lib/route_translator/extensions/mapper.rb
lib/route_translator/translator.rb
test/dummy/app/controllers/blorgh/posts_controller.rb
test/dummy/app/controllers/dummy_controller.rb
test/dummy/config/application.rb
test/dummy/config/routes.rb
test/integration/generated_path_test.rb

close https://github.com/enriclluelles/route_translator/issues/123
For following routes,
```rb
localized do
mount Blorgh::Engine, at: '/blorgh'
end
```
this patch defines `blorgh_en`, `blorgh_es`, `blorgh_ru`, ... to `Rails.application.routes.mounted_helpers`, instead of broken `blorgh`.
Even with this fix, only one of `blorgh_en`, `blorgh_es`, ... works because of https://github.com/rails/rails/issues/27352. But it's Rails' bug and I think route_translator should have this change.
What do you think? @tagliala

Localize mounted helper

---

README.md
lib/route_translator/extensions/route_set.rb
lib/route_translator/route.rb
lib/route_translator/translator.rb
lib/route_translator/translator/path.rb
lib/route_translator/translator/path/segment.rb
test/locales/routes.yml
test/routing_test.rb

Add an ability to translate controllers with namespaces.

---

README.md
lib/route_translator.rb
lib/route_translator/extensions/route_set.rb
lib/route_translator/host_path_consistency_lambdas.rb
lib/route_translator/translator.rb
test/integration/host_locale_path_verify_consistency_test.rb
test/support/configuration_helper.rb

When using different hosts to identify different locales, it's
desirable to ensure that only coherent url's work on the application.
Mismatching between the locale assigned to a domain (ej: example.es) and
the language of the path (ej: '/cesta-de-la-compra') should be considered
404's.
This commit adds a configuration option to enable this behavior.

Add verify_host_path_consistency option

---

lib/route_translator/translator/path/segment.rb
test/dummy/app/controllers/dummy_controller.rb
test/dummy/config/locales/all.yml
test/dummy/config/routes.rb
test/integration/generated_path_test.rb
test/locales/routes.yml
test/routing_test.rb

Hi!
First: Thanks for maintaining this gem!
After updating to the lastest version i've noticed a breaking change regarding handling of slashes in translation files. Some investigation showed that the commit dc77562 changed the behaviour how the translated paths are escaped.
While avoiding `URI.escape` is desirable, such a big change in the way translated paths are handled should maybe happen in a major gem update?
I'm open to different solutions and i've started to avoid slashes in translation files, but maybe we should restore the old behaviour for now and change this in a bigger update?

Partially restore URI.escape behaviour to avoid breaking change

---

CHANGELOG.md
lib/route_translator/extensions/route_set.rb

PR rails/rails#34656 has recently been merged to rails master and
backported to the rails 6-0-stable branch. It added an extra argument
to the Mapper::Mapping.new method which makes it incompatible with the
current version of route_translator 
This change is going to use `Mapper::Mapping.build` instead of
`Mapper::Mapping.new` because the former preserved its signature across
all Rails versions
Fix: #195
Ref: rails/rails@85855d63fc

Add Rails > 6.0.0.rc1 compatibility

---

README.md
lib/route_translator.rb
test/helpers/helper_test.rb
test/integration/generated_path_test.rb
test/integration/routing_test.rb
test/integration/thread_safety_test.rb
test/routing_test.rb
test/support/configuration_helper.rb
test/support/i18n_helper.rb
test/test_case_helpers_test.rb

Keeps the default settings in a single place, instead of having it in
both `route_translator.rb` and `configuration_helper.rb`
There is no `default_locale` setting in Route Translator.
The previous method was just an alias for `I18n.default_locale`.
This change will remove this ambiguity and change i18n helpers
to properly reset default locale between tests

Feature: Refactor Configuration

---

CHANGELOG.md
lib/route_translator.rb
lib/route_translator/extensions/action_controller.rb
lib/route_translator/host.rb
test/dummy/app/controllers/dummy_controller.rb
test/dummy/config/routes.rb
test/host_test.rb
test/integration/invalid_locales_test.rb

When a user passes an invalid locale to an unlocalized route (such as
ActiveStorage routes or routes outside the `localized` block),
`route_translator` does not check if the locale is included in the
available locales list and a default Rails configuration will raise
an InvalidLocale error.
This behaviour could potentially open to DOS attacks (eg: flooding an
exception tracker)
This commit will prevent to set locales that are not included in
`I18n.available_locales`
Close: #196

Do not raise InvalidLocale errors

---

lib/route_translator/extensions/route_set.rb
test/dummy/app/controllers/account/foo_controller.rb
test/dummy/config/locales/all.yml
test/dummy/config/routes.rb
test/integration/namespace_test.rb

The dup of the `blocks` argument was removed on the last refactor of the route_set, but it was necessary. On the other hand, `defaults` doesn't need a dup since this is already done inside `::ActionDispatch::Routing::Mapper::Mapping.build`.
The new test showcases the bug (404 response) with the previous code.

FIX: missing dup on blocks

---

lib/route_translator/extensions/action_controller.rb
lib/route_translator/extensions/test_case.rb

I found that the `ActiveSupport.on_load(:action_controller)` wasn't working as intented because `action_controller` was require on top.
I figured that requiring `test_case` only when needed would fix that small issue

Fixed lazy load action controller

---

lib/route_translator/extensions/mapper.rb

I get a bunch of these when updating to Rails 6.1.0.rc1 (using route_translator 8.2.0, following the merge of #210):
```
DEPRECATION WARNING: URI.parser is deprecated and will be removed in Rails 6.2. Use `URI::DEFAULT_PARSER` instead.  (called from block (3 levels) in <top (required)> at .../config/routes.rb:77)
```
The stack trace points to various routes defined within the `localized do ... end` blocks present in my routing file, but nothing more specific. However I see a single instance of `URI.parser` in this gem's source code, so I guess this is it.

URI.parser is deprecated and will be removed in Rails 6.2

---

Appraisals
gemfiles/rails_6.0.gemfile
gemfiles/rails_6.1.gemfile
gemfiles/rails_edge.gemfile

net-smtp has been removed from default gems in Ruby 3.1, but it is used
by the `mail` gem.
Remove when mikel/mail#1439 is fixed

Add net-smtp gem explicitly

---

lib/route_translator/translator/path/segment.rb
test/routing_test.rb

1. Do not enable fallback if disable_fallback option is enabled
2. Raise if the translation is not found, so that `translate_path` may
rescue from it
Close #241
TODO:

Fix disable fallback behavior

---

.github/workflows/rubocop.yml
.github/workflows/ruby.yml

Workflows run with extended set of permissions by default. By specifying any permission explicitly, all others are set to none.
Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

Add explicit permissions to workflows

---

README.md
lib/route_translator.rb
lib/route_translator/route.rb
test/integration/i18n_slash_separator_test.rb
test/locales/routes.yml
test/routing_test.rb

Add option for standard nested separator
This commit adds a new configuration option called `i18n_use_slash_separator`
to the Route Translator gem. This option controls whether or not to use the `/`
separator for nested route names in the gem's translation files.
The approach used in Route Translator was to remove the slash and prefer
a nested key. However, this commit changes the default separator to a slash
(`/`) character to match Rails' nested route syntax.
The old approach of using a nested key instead of a separator would have
prevented the following scenario:
```rb
Rails.application.routes.draw do
localized do
resources :appointments, only: :index do
post :reservations, on: :member
end
namespace :appointments do
resources :reservations, only: :index
end
end
end
```
because of the …

Add support for i18n lookup with the controller path instead of nested keys

---

CHANGELOG.md
lib/route_translator.rb
lib/route_translator/railtie.rb
lib/route_translator/version.rb

While adding the new initializer generator, an unneeded railtie was included by mistake
This commit removes the railtie
Fix #296

Remove unneeded railtie

---

lib/route_translator/translator/route_helpers.rb

I noticed some weird memory usage in development and also request becoming slower every time I changed a file in my rails project.
After some digging I found this gem to be the issue. 
In this PR https://github.com/enriclluelles/route_translator/pull/284 this code was introduced. For some reason the check `if ENV.fetch('RAILS_ENV', nil) == 'test'` was removed. This made by development env very slow and it consumed a lot of memory.
We can just add this check back right?
example in rails console:
With current version:
```
25.times { puts Benchmark.realtime { Rails.application.routes.clear!; Rails.application.routes_reloader.execute } }
1.07533899997361
1.1278870000387542
1.1042030000244267
1.332025000010617
1.351589999976568
1.416763000015635
1.560079999966547
1.6818230000208132 …
```

Memory leak in development mode

---

test/routing_test.rb

Rails Edge produced some warnings:
- Test is missing assertions: `test_action_controller_gets_locale_setter`
- Test is missing assertions: `test_action_controller_gets_locale_suffix_helper`
- Test is missing assertions: `test_action_view_gets_locale_suffix_helper`
Those tests never worked because the assertion was missing (they were returning false) and broke at a certain point in time

Fix "Test is missing assertions" warnings

---

route_translator.gemspec

We're unable to test our project with edge Rails at the moment as route_translator doesn't officially support anything newer than 7.1 and the next version of Rails will be 8.0.
Ran the existing test suite against edge and they all seem to pass.

Allow Rails 8.0

---

lib/route_translator.rb
lib/route_translator/extensions.rb
lib/route_translator/translator.rb
lib/route_translator/translator/path.rb

`require_relative` is preferred over `require` for files within the same project because it uses paths relative to the current file, making code more portable and less dependent on the load path.
This change updates internal requires to use `require_relative` for consistency, performance, and improved portability.
Refs:
- rubocop/rubocop#8748

Prefer `require_relative` for internal requires

---

.rubocop.yml
Appraisals
gemfiles/rails_6.1.gemfile
gemfiles/rails_7.0.gemfile
gemfiles/rails_7.1.gemfile
gemfiles/rails_7.2.gemfile
gemfiles/rails_8.0.gemfile
gemfiles/rails_edge.gemfile

They do not inherit from base when `AllCops` rule is being configured, this will speed up execution

Fix RuboCop exclusions
